#!/usr/bin/env bash
# script that configure the server not found status
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/Sackitey68/ permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
