#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".

step=0

while [ $step -lt 10 ]
do
  if [ $step -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( step++ ))
done
