#!/usr/bin/env bash
# commands used install ufw and enable ports 22, 443, 8080

sudo apt-get update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 8080
sudo ufw -y enable
